#!/usr/bin/env python3
"""PreToolUse hook — enforce the hub's hard rules before a tool runs.

Denials (everything else is allowed to proceed to normal permissioning):
  * editing docs/generated/**            — regenerated by workflows, never by hand
  * writing into the workspace/ mirror   — feature work belongs in a git worktree
  * reading the secrets shim (.claude/hub-env)
  * destructive git against the mirror   — reset --hard / clean -f / push --force
"""

from __future__ import annotations

import re

from _common import HUB_ROOT, deny, read_event  # noqa: E402

_DESTRUCTIVE_GIT = re.compile(
    r"git\b.*\b(reset\s+--hard|clean\s+-[a-z]*f|push\s+(--force|-f)\b|checkout\s+--\s)"
)
_SECRET_SUFFIX = ".claude/hub-env"


def _file_denial(file_path: str) -> str | None:
    from hub_lib import paths

    if not file_path:
        return None
    if paths.is_generated_doc(file_path, HUB_ROOT):
        return "docs/generated/ is regenerated by workflows — edit the generating workflow, not the output."
    if paths.is_workspace_path(file_path, HUB_ROOT) and not paths.is_worktree_path(
        file_path
    ):
        return "workspace/ is a pristine mirror. Do feature work in a git worktree (EnterWorktree / using-git-worktrees), not the clone."
    return None


_SECRET_MSG = (
    "That file holds secrets (GITLAB_TOKEN). Do not read or edit it into context."
)
_FILE_TOOLS = ("Edit", "Write", "MultiEdit", "NotebookEdit")


def _bash_denial(command: str) -> str | None:
    if not command:
        return None
    if _SECRET_SUFFIX in command.replace("\\", "/"):
        return _SECRET_MSG
    if "workspace/" in command and _DESTRUCTIVE_GIT.search(command):
        return "Refusing destructive git against the workspace/ mirror. Operate inside a worktree instead."
    return None


def evaluate(tool_name: str, tool_input: dict) -> str | None:
    if tool_name in _FILE_TOOLS:
        path = tool_input.get("file_path") or tool_input.get("notebook_path") or ""
        if path.replace("\\", "/").endswith(_SECRET_SUFFIX):
            return _SECRET_MSG
        return _file_denial(path)
    if tool_name == "Bash":
        return _bash_denial(tool_input.get("command", ""))
    return None


def main() -> int:
    event = read_event()
    try:
        reason = evaluate(event.get("tool_name", ""), event.get("tool_input", {}) or {})
    except Exception:  # on error, don't block — fail open
        reason = None
    if reason:
        deny(reason)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
