# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""scaffold_docs.py — create (or top up) the curated ``docs/`` vault.

Idempotent: creates any missing folder, README or bookkeeping file and never
overwrites existing curated content (use ``--force`` to rewrite the seed
READMEs). Run once to bootstrap; safe to re-run.

    uv run workflows/scaffold_docs.py [--force]
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from hub_lib import paths  # noqa: E402

# folder -> (title, type, one-line purpose, "answers" bullet lines)
FOLDERS: dict[str, tuple[str, str, str, list[str]]] = {
    "graph": (
        "Project graph",
        "graph",
        "Nodes and relationships of the workspace: repos, services, packages, databases, external systems.",
        [
            "Which repository owns this capability?",
            "What is upstream/downstream of this component?",
        ],
    ),
    "architecture": (
        "Architecture",
        "architecture",
        "Current architectural descriptions and durable design rationale.",
        ["How do the systems fit together?", "What constraints must hold?"],
    ),
    "architecture/decisions": (
        "Architecture decisions (ADRs)",
        "decision",
        "Durable decisions with context, alternatives and consequences.",
        ["Why was this chosen over the alternatives?"],
    ),
    "domain": (
        "Domain knowledge",
        "domain",
        "Terminology, entities, business rules and invariants not inferable from structure alone.",
        ["What invariant must remain true?", "What does this status mean?"],
    ),
    "workflows": (
        "Workflows",
        "workflow",
        "Normal end-to-end system workflows: trigger, stages, artefacts, completion.",
        ["How does this workflow normally progress?"],
    ),
    "runbooks": (
        "Runbooks",
        "runbook",
        "Operational procedures for abnormal situations: diagnosis and recovery.",
        ["What do I do when this workflow fails?"],
    ),
    "interfaces": (
        "Interfaces",
        "interface",
        "Contracts between components: APIs, events, queues, schemas, compatibility.",
        ["What contract connects these systems?"],
    ),
    "operations": (
        "Operations",
        "operations",
        "Knowledge required to run systems in production.",
        ["How is this deployed and observed?"],
    ),
    "development": (
        "Development",
        "development",
        "Contributor-facing engineering guidance and hard-to-discover commands.",
        ["How do I set up and test this locally?"],
    ),
    "generated": (
        "Generated documentation",
        "development",
        "Mechanically derived docs. DO NOT hand-edit — regenerated by workflows.",
        ["What is the current inventory/index?"],
    ),
    "memory": (
        "Documentation memory",
        "development",
        "Bookkeeping that keeps curated docs in sync with source. Not project documentation.",
        ["What doc impact is still unresolved?"],
    ),
}

GRAPH_SUBDIRS = [
    "repositories",
    "services",
    "packages",
    "databases",
    "external-systems",
]


def front_matter(title: str, kind: str, *, generated: bool = False) -> str:
    return (
        "---\n"
        f"title: {title}\n"
        f"type: {kind}\n"
        "status: current\n"
        "owners: []\n"
        "systems: []\n"
        "source_paths: []\n"
        "related: []\n"
        "last_verified: \n"
        f"generated: {'true' if generated else 'false'}\n"
        "---\n\n"
    )


def readme_body(title: str, purpose: str, answers: list[str]) -> str:
    bullets = "\n".join(f"- {a}" for a in answers)
    return (
        f"# {title}\n\n{purpose}\n\n"
        "## Questions this folder answers\n\n"
        f"{bullets}\n\n"
        "## Front-matter\n\n"
        "Every curated note starts with the shared front-matter block above. "
        "Fill `owners`, `systems`, `source_paths` and set `last_verified` only "
        "after inspecting the referenced source.\n"
    )


def write_if_absent(path: Path, content: str, force: bool) -> bool:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and not force:
        return False
    path.write_text(content, encoding="utf-8")
    return True


def scaffold(hub_root: Path, force: bool) -> list[str]:
    docs = paths.docs_dir(hub_root)
    created: list[str] = []

    for rel, (title, kind, purpose, answers) in FOLDERS.items():
        readme = docs / rel / "README.md"
        gen = rel in ("generated", "memory")
        content = front_matter(title, kind, generated=gen) + readme_body(
            title, purpose, answers
        )
        if write_if_absent(readme, content, force):
            created.append(str(readme.relative_to(hub_root)))

    for sub in GRAPH_SUBDIRS:
        keep = docs / "graph" / sub / ".gitkeep"
        if write_if_absent(keep, "", force=False):
            created.append(str(keep.relative_to(hub_root)))

    created += _seed_memory(hub_root)
    if write_if_absent(docs / "README.md", _vault_index(), force):
        created.append("docs/README.md")
    return created


def _seed_memory(hub_root: Path) -> list[str]:
    mem = paths.memory_dir(hub_root)
    created: list[str] = []
    seeds = {
        "pending-updates.jsonl": "",
        "stale-docs.json": json.dumps({"generated_at": None, "stale": []}, indent=2)
        + "\n",
        "last-validation.json": json.dumps(
            {"generated_at": None, "errors": []}, indent=2
        )
        + "\n",
    }
    for name, content in seeds.items():
        if write_if_absent(mem / name, content, force=False):
            created.append(str((mem / name).relative_to(hub_root)))
    return created


def _vault_index() -> str:
    rows = "\n".join(f"- `docs/{rel}/` — {spec[2]}" for rel, spec in FOLDERS.items())
    return (
        front_matter("Docs vault index", "development")
        + "# Curated knowledge vault\n\n"
        "Layer-2 memory for the hub: **what the workspace systems are, how they "
        "work, and why**. Authoritative for current project knowledge (see the "
        "source-of-truth precedence in `CLAUDE.md`).\n\n"
        "## Git policy\n\n"
        "`docs/` is tracked **except** `docs/generated/**` and `docs/memory/**` "
        "(reproducible / machine-local bookkeeping, git-ignored aside from their "
        "READMEs). Curated knowledge is shared and reviewable in git.\n\n"
        "## Folders\n\n"
        f"{rows}\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--force", action="store_true", help="rewrite seed READMEs")
    args = parser.parse_args()

    hub_root = paths.find_hub_root(Path.cwd())
    created = scaffold(hub_root, args.force)
    if created:
        print(f"scaffolded {len(created)} file(s):")
        for f in created:
            print(f"  + {f}")
    else:
        print("vault already complete — nothing to do.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
